# Generated by Django 6.0.7 on 2026-07-11 17:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_date', models.DateField()),
                ('vendor_challan_number', models.CharField(max_length=100)),
                ('number_of_rolls', models.PositiveIntegerField(default=0)),
                ('vendor_metres', models.DecimalField(decimal_places=3, max_digits=12)),
                ('factory_measured_metres', models.DecimalField(decimal_places=3, max_digits=12)),
                ('vendor_weight', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('factory_measured_weight', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('rejected_metres', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('accepted_metres', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('metre_difference', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('weight_difference', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('production_lot_number', models.CharField(max_length=50, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_checked', to='master_data.employee')),
                ('cloth_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='master_data.clothtype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_received', to='master_data.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='master_data.vendor')),
            ],
            options={
                'ordering': ['-receipt_date', '-id'],
            },
        ),
    ]
