# Generated by Django 6.0.7 on 2026-07-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothreceipt',
            name='production_lot_number',
            field=models.CharField(help_text='Main lot / palli number used across all production stages.', max_length=50, unique=True, verbose_name='Lot Number / Palli Number'),
        ),
    ]
