# Generated by Django 6.0.7 on 2026-07-13 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('receiving', '0002_alter_clothreceipt_production_lot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothreceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_received', to='master_data.employee'),
        ),
    ]
