# Generated by Django 5.2.16 on 2026-07-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0003_remove_required_received_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothreceipt',
            name='factory_number_of_rolls',
            field=models.PositiveIntegerField(default=0, verbose_name='Factory Thaan (فیکٹری تھان)'),
        ),
        migrations.AlterField(
            model_name='clothreceipt',
            name='factory_measured_metres',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Factory M (فیکٹری میٹر)'),
        ),
        migrations.AlterField(
            model_name='clothreceipt',
            name='number_of_rolls',
            field=models.PositiveIntegerField(default=0, verbose_name='Party Thaan (پارٹی تھان)'),
        ),
        migrations.AlterField(
            model_name='clothreceipt',
            name='vendor_metres',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Vendor M (وینڈر میٹر)'),
        ),
    ]
