# Generated by Django 5.2.16 on 2026-07-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0004_add_factory_number_of_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothreceipt',
            name='vendor_challan_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
