# Generated by Django 5.2.16 on 2026-07-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0005_challan_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothreceipt',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Optional photo — compressed automatically to save space.', null=True, upload_to='receiving/%Y/%m/', verbose_name='Photo'),
        ),
    ]
