# Generated by Django 5.2.16 on 2026-07-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0006_add_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothreceipt',
            name='factory_measured_metres',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Factory M (فیکٹری گزانہ)'),
        ),
        migrations.AlterField(
            model_name='clothreceipt',
            name='vendor_metres',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Vendor M (پارٹی گزانہ)'),
        ),
    ]
