# Generated by Django 5.2.16 on 2026-07-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0007_metres_urdu_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothreceipt',
            name='factory_measured_metres',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Factory M (فیکٹری غزانہ)'),
        ),
        migrations.AlterField(
            model_name='clothreceipt',
            name='vendor_metres',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Vendor M (پارٹی غزانہ)'),
        ),
    ]
