# Generated by Django 5.2.16 on 2026-07-19 10:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0008_ghazana_spelling'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothreceipt',
            name='pv_blend_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='PV blend'),
        ),
        migrations.AddField(
            model_name='clothreceipt',
            name='read_pick_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Read Pick'),
        ),
    ]
