# Generated by Django 5.2.16 on 2026-07-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0009_cloth_type_both_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothreceipt',
            name='factory_number_of_rolls',
            field=models.PositiveIntegerField(default=0, verbose_name='Factory Thaan (فیکٹری تھان نمبر)'),
        ),
        migrations.AlterField(
            model_name='clothreceipt',
            name='number_of_rolls',
            field=models.PositiveIntegerField(default=0, verbose_name='Party Thaan (پارٹی تھان نمبر)'),
        ),
        migrations.AlterField(
            model_name='clothreceipt',
            name='pv_blend_qty',
            field=models.CharField(blank=True, default='', help_text='Amount or code — digits and / allowed (e.g. 80 or 80/40). Use / for blank.', max_length=50, verbose_name='PV blend'),
        ),
        migrations.AlterField(
            model_name='clothreceipt',
            name='read_pick_qty',
            field=models.CharField(blank=True, default='', help_text='Amount or code — digits and / allowed (e.g. 80 or 80/40). Use / for blank.', max_length=50, verbose_name='Read Pick'),
        ),
    ]
