# Generated by Django 5.2.16 on 2026-07-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0010_cloth_qty_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothreceipt',
            name='factory_measured_weight',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Factory wt'),
        ),
        migrations.AlterField(
            model_name='clothreceipt',
            name='vendor_weight',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Vendor wt'),
        ),
    ]
