# Generated by Django 5.2.16 on 2026-07-27 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('gate_number', models.CharField(help_text='Auto numbers like G1, G2, G3…', max_length=20, unique=True, verbose_name='Gate No.')),
                ('entry_date', models.DateField(verbose_name='Date')),
                ('purchaser', models.CharField(max_length=200, verbose_name='Purchaser')),
                ('shop_name', models.CharField(max_length=200, verbose_name='Shop Name')),
                ('chemical', models.CharField(blank=True, default='', max_length=255, verbose_name='Chemical')),
                ('electrical', models.CharField(blank=True, default='', max_length=255, verbose_name='Electrical')),
                ('mechanical', models.CharField(blank=True, default='', max_length=255, verbose_name='Mechanical')),
                ('general', models.CharField(blank=True, default='', max_length=255, verbose_name='General')),
                ('demanded_by', models.CharField(max_length=200, verbose_name='Demanded By')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gate Entry',
                'verbose_name_plural': 'Gate Entries',
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
