# Generated by Django 6.0.7 on 2026-08-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_entry', '0002_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateentry',
            name='entry_image',
            field=models.ImageField(blank=True, help_text='Optional photo — compressed automatically to save space.', null=True, upload_to='gate_entry/%Y/%m/', verbose_name='Photo'),
        ),
    ]
