# Generated by Django 5.2.16 on 2026-09-09 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('gate_entry', 'Gate Entry'), ('receiving', 'Cloth Receiving'), ('production_lots', 'Production Lots'), ('singeing', 'Singeing'), ('dyeing', 'Dyeing'), ('six_chamber', 'Six Chamber'), ('calender', 'Calender'), ('comfort', 'Comfort'), ('finished_stock', 'Finished Stock'), ('inventory', 'Purchases & Stock'), ('chemicals', 'Chemicals'), ('electricity', 'Electricity'), ('maintenance', 'Maintenance'), ('attendance', 'Attendance')], max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'module'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
