# Generated by Django 5.2.16 on 2026-09-09 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassignment',
            name='module',
            field=models.CharField(choices=[('gate_entry', 'Gate Entry'), ('receiving', 'Cloth Receiving'), ('production_lots', 'Production Lots'), ('singeing', 'Singeing'), ('dyeing', 'Dyeing'), ('six_chamber', 'Six Chamber'), ('calender', 'Calender'), ('comfort', 'Comfort'), ('finished_stock', 'Finished Stock'), ('inventory', 'Purchases & Stock'), ('chemicals', 'Chemicals'), ('electricity', 'Electricity'), ('maintenance', 'Maintenance'), ('attendance', 'Attendance'), ('fuel', 'Fuel')], max_length=50),
        ),
        migrations.CreateModel(
            name='PermanentDeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=50)),
                ('object_pk', models.PositiveIntegerField()),
                ('module', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for admin'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_delete_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_delete_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('model_key', 'object_pk'), name='unique_pending_permanent_delete')],
            },
        ),
    ]
