# Generated by Django 6.0.7 on 2026-07-11 17:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('master_data', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('transaction_number', models.CharField(max_length=50, unique=True)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Dyeing Usage', 'Dyeing Usage'), ('Mixture Usage', 'Mixture Usage'), ('Maintenance Usage', 'Maintenance Usage'), ('Adjustment In', 'Adjustment In'), ('Adjustment Out', 'Adjustment Out'), ('Return', 'Return'), ('Reversal', 'Reversal')], max_length=50)),
                ('quantity_in', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('quantity_out', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('related_reference', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dyeing_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='production.dyeingbatch')),
                ('dyeing_material_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='production.dyeingmaterialusage')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_transactions_entered', to=settings.AUTH_USER_MODEL)),
                ('maintenance_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='maintenance.maintenancejob')),
                ('maintenance_material_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='maintenance.maintenancematerialusage')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='master_data.material')),
                ('mixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='production.mixture')),
                ('reversed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.materialtransaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(fields=['material', 'transaction_date'], name='inventory_m_materia_8f0bdf_idx'), models.Index(fields=['transaction_type'], name='inventory_m_transac_4f73d9_idx')],
            },
        ),
    ]
