# Generated by Django 6.0.7 on 2026-08-13 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalIssueSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('issue_date', models.CharField(max_length=50, verbose_name='Date')),
                ('issue_slip_number', models.CharField(max_length=100, verbose_name='Issue Slip Number')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('department', models.CharField(max_length=200, verbose_name='Department')),
                ('weight_kgs', models.CharField(blank=True, default='', max_length=100, verbose_name='Weight (kgs)')),
                ('lot_number', models.CharField(blank=True, default='', max_length=100, verbose_name='LOT NO.')),
                ('jet_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Jet No.')),
                ('jigar_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Jigar No.')),
                ('total_issued', models.CharField(blank=True, default='', max_length=100, verbose_name='Total Issued')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chemical Issue Slip',
                'verbose_name_plural': 'Chemical Issue Slips',
                'ordering': ['-id'],
            },
        ),
    ]
