# Generated by Django 6.0.7 on 2026-08-13 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_chemical_issue_slip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stock_date', models.CharField(max_length=50, verbose_name='Date')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('closing_stock', models.CharField(blank=True, default='', max_length=100, verbose_name='Closing Stock')),
                ('new_stock', models.CharField(blank=True, default='', max_length=100, verbose_name='New Stock')),
                ('total_stock', models.CharField(blank=True, default='', max_length=100, verbose_name='Total Stock')),
                ('issued_stock', models.CharField(blank=True, default='', max_length=100, verbose_name='Issued Stock')),
                ('remaining_stock', models.CharField(blank=True, default='', max_length=100, verbose_name='Remaining Stock')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chemical Stock',
                'verbose_name_plural': 'Chemical Stock',
                'ordering': ['-id'],
            },
        ),
    ]
