# Generated by Django 6.0.7 on 2026-07-11 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('maintenance_type', models.CharField(choices=[('Preventive Maintenance', 'Preventive Maintenance'), ('Corrective Maintenance', 'Corrective Maintenance'), ('Breakdown', 'Breakdown'), ('Inspection', 'Inspection')], max_length=50)),
                ('reported_datetime', models.DateTimeField()),
                ('fault_category', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Hydraulic', 'Hydraulic'), ('Pneumatic', 'Pneumatic'), ('Heating', 'Heating'), ('Motor', 'Motor'), ('Bearing', 'Bearing'), ('Sensor', 'Sensor'), ('Control Panel', 'Control Panel'), ('Other', 'Other')], max_length=50)),
                ('fault_description', models.TextField()),
                ('repair_started_datetime', models.DateTimeField(blank=True, null=True)),
                ('repair_completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('machine_restarted_datetime', models.DateTimeField(blank=True, null=True)),
                ('repair_description', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('In Progress', 'In Progress'), ('Fixed', 'Fixed'), ('Closed', 'Closed')], default='Reported', max_length=50)),
                ('previous_repair_date', models.DateTimeField(blank=True, null=True)),
                ('days_since_previous_repair', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_jobs', to='master_data.machine')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_reported', to='master_data.employee')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_technician', to='master_data.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_datetime', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('usage_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('maintenance_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_usages', to='maintenance.maintenancejob')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_usages', to='master_data.material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_date', '-id'],
            },
        ),
    ]
