# Generated by Django 6.0.7 on 2026-09-09 14:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamboilershiftrecord',
            name='kuttal_daily_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Kuttal Daily Price'),
        ),
        migrations.AddField(
            model_name='steamboilershiftrecord',
            name='lunda_daily_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Lunda Daily Price'),
        ),
        migrations.AddField(
            model_name='steamboilershiftrecord',
            name='total_daily_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total Daily Price'),
        ),
    ]
