# Generated by Django 6.0.7 on 2026-09-09 15:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_steamboilershiftrecord_kuttal_daily_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OilBoilerShiftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_date', models.DateField(db_index=True, verbose_name='Date')),
                ('shift', models.PositiveSmallIntegerField(choices=[(1, 'Shift 1'), (2, 'Shift 2')], verbose_name='Shift')),
                ('run_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Run Time (hours)')),
                ('kuttal_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Kuttal Quantity')),
                ('kuttal_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Kuttal Price')),
                ('kuttal_daily_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Kuttal Daily Price')),
                ('lunda_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Lunda Quantity')),
                ('lunda_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Lunda Price')),
                ('lunda_daily_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Lunda Daily Price')),
                ('fuel_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Fuel Quantity')),
                ('fuel_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Fuel Price')),
                ('fuel_daily_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Fuel Daily Price')),
                ('total_daily_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total Daily Price')),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oil Boiler Shift Record',
                'verbose_name_plural': 'Oil Boiler Shift Records',
                'ordering': ['-record_date', 'shift', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cancelled', False), ('is_deleted', False)), fields=('record_date', 'shift'), name='unique_active_oil_boiler_shift_per_day')],
            },
        ),
    ]
