# Generated by Django 6.0.7 on 2026-07-11 17:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('meter_number', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('multiplier', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_meters', to='master_data.machine')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('reading_date', models.DateField()),
                ('opening_reading', models.DecimalField(decimal_places=3, max_digits=12)),
                ('closing_reading', models.DecimalField(decimal_places=3, max_digits=12)),
                ('multiplier', models.DecimalField(decimal_places=3, max_digits=8)),
                ('units_consumed', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electricity_readings_checked', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electricity_readings_entered', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='electricity.electricitymeter')),
            ],
            options={
                'ordering': ['-reading_date', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cancelled', False)), fields=('reading_date', 'meter'), name='unique_active_reading_per_meter_date')],
            },
        ),
    ]
