# Generated by Django 5.2.16 on 2026-09-09 19:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0002_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_date', models.DateField()),
                ('source_mode', models.CharField(choices=[('wapda', 'WAPDA only'), ('wapda_solar', 'WAPDA + Solar')], default='wapda', max_length=20)),
                ('wapda_peak_kwh', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('wapda_offpeak_kwh', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('solar_kwh', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('peak_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('offpeak_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('wapda_total_kwh', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('total_kwh', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('remarks', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cancelled', False), ('is_deleted', False)), fields=('record_date',), name='unique_active_power_reading_per_date')],
            },
        ),
    ]
