# Generated by Django 6.0.7 on 2026-07-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_unit', models.CharField(choices=[('Metre', 'Metre'), ('Kg', 'Kg')], default='Metre', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('machine_type', models.CharField(choices=[('Singeing', 'Singeing'), ('Jet Dyeing', 'Jet Dyeing'), ('Six Chamber', 'Six Chamber'), ('Calender', 'Calender'), ('Comfort', 'Comfort'), ('Electricity Meter', 'Electricity Meter'), ('Other', 'Other')], max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Under Maintenance', 'Under Maintenance'), ('Broken Down', 'Broken Down'), ('Inactive', 'Inactive')], default='Running', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Chemical', 'Chemical'), ('Dye', 'Dye'), ('Oil', 'Oil'), ('Grease', 'Grease'), ('Maintenance Item', 'Maintenance Item'), ('Other', 'Other')], max_length=50)),
                ('unit', models.CharField(choices=[('Kilogram', 'Kilogram'), ('Litre', 'Litre'), ('Gram', 'Gram'), ('Piece', 'Piece'), ('Bag', 'Bag'), ('Drum', 'Drum')], max_length=20)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
