# Generated by Django 6.0.7 on 2026-08-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Chemical', 'Chemical'), ('Dye', 'Dye'), ('Oil', 'Oil'), ('Grease', 'Grease'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Maintenance Item', 'Maintenance Item'), ('Other', 'Other')], max_length=50),
        ),
    ]
