# Generated by Django 6.0.7 on 2026-08-13 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department_slug', models.CharField(db_index=True, max_length=50)),
                ('section_slug', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('row_number', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('father_name', models.CharField(blank=True, default='', max_length=200)),
                ('total_overtime_hours', models.CharField(blank=True, default='', max_length=50)),
                ('work_status', models.CharField(blank=True, default='', max_length=100)),
                ('decided_salary', models.CharField(blank=True, default='', max_length=50)),
                ('total_hours', models.CharField(blank=True, default='', max_length=50)),
                ('days_data', models.JSONField(blank=True, default=dict)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Row',
                'verbose_name_plural': 'Attendance Rows',
                'ordering': ['row_number', 'id'],
                'indexes': [models.Index(fields=['department_slug', 'section_slug'], name='attendance__departm_33987f_idx')],
            },
        ),
    ]
